app:
  page_size: 20
source:
  type: "db"
  database:
    name: "abc"
    address: "127.0.0.1"
    port: 3306
    account: "root"
    password: "1234567890"
target:
  type: "db"
  database:
    name: "ha666db"
    address: "127.0.0.1"
    port: 3306
    account: "root"
    password: "1234567890"
